version: '3'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
